# Generated by Django 4.2.23 on 2025-08-21 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookshelf", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="book",
            options={
                "permissions": [
                    ("can_view", "Can view book"),
                    ("can_create", "Can create book"),
                    ("can_edit", "Can edit book"),
                    ("can_delete", "Can delete book"),
                ]
            },
        ),
    ]
