# Generated by Django 4.2.23 on 2025-08-18 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("relationship_app", "0002_userprofile"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="book",
            options={
                "permissions": (
                    ("can_add_book", "Can add book"),
                    ("can_change_book", "Can change book"),
                    ("can_delete_book", "Can delete book"),
                )
            },
        ),
        migrations.AddField(
            model_name="book",
            name="publication_year",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
